### ISSUE TITLE
.NET Standard / Core support?

### ISSUE THREAD

**Issue by kinetiq** [zzzprojects/Z.ExtensionMethods#10]
I'm having trouble finding any statements on whether you support, or plan to support, .NET Standard / Core moving forward. 

I'm getting a compatibility warning in my project though, so I'm guessing Z.ExtensionMethods currently is only for Full Framework, is that right?

**Comment by JonathanMagnan** [comment]
Hello @kinetiq ,

Yes, you are right. It currently works on the full framework.

We will for sure support eventually .NET Standard but I'm not sure yet when in `2018` since we are currently re-writing some other libraries which will take us already some month.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
After some discussion (28 seconds later),

We will try to look at it next week to at least see the effort to support .NET Standard 2.0

We could do it in two phases:
- Phase 1: Support .NET Standard (Now)
- Phase 2: Cleanup & Rewrite the library (later in 2018)

We will give you more information probably next week.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by kinetiq** [comment]
Just a quick note that when I updated my open source libraries to Standard, it wasn't that bad. But anything with reflection is going to change a bit - mostly just namespace naming.

**Comment by kinetiq** [comment]
How is this project going? :)

**Comment by Ricky-G** [comment]
Keen to see support for .NET Standard 2 :-)

**Comment by JonathanMagnan** [comment]
Hello @kinetiq , @Ricky-G ,

My developer made the change a few weeks ago but unfortunately, I got some health issue, so a lot of free requests has been paused like this one.

I will try to review his code next weekend and make a release from it.

Best Regards,

Jonathan

**Comment by kinetiq** [comment]
Thanks - really looking forward to this!

**Comment by kinetiq** [comment]
Since over 6 months have passed, I was wondering if this is going to happen or if we should just give up on z for future versions of .net?

**Comment by JonathanMagnan** [comment]
Hello @kinetiq ,

I was going yesterday to answer that I will work on it this weekend but I guess I lost this right ;)

So I will instead tell you that the v2.1.0 has been released.

It now supports .NET Standard.

Thank a lot for the patience and reminder from time to time ;)

Let me know if everything is working as expected.

Best Regards,

Jonathan

**Comment by kinetiq** [comment]
Hey, that's great! Thanks for the heads up!

**Comment by JonathanMagnan** [comment]
Hello @kinetiq ,

This issue will be closed since it has been completed.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
