### ISSUE TITLE
 Lack of namespaces?

### ISSUE THREAD

**Issue by jonleigh** [zzzprojects/Z.ExtensionMethods#11]
Is there a reason you decided not to use namespaces?  

The good is that the extension methods are available everywhere but the bad is that the take precedence over methods with the same name, even if that's not what you want (when using the RavenDB Linq extension methods for instance).

**Comment by JonathanMagnan** [comment]
Hello @jonleigh ,

There is 5 version of this library:

Full Version | NuGet
------------ | :-------------:
Z.ExtensionMethods **_(Recommended)_**       | <a href="https://www.nuget.org/packages/Z.ExtensionMethods/" target="_blank"><img src="https://zzzprojects.github.io/images/nuget/extension-methods-v.svg" alt="download" /></a> <a href="https://www.nuget.org/packages/Z.ExtensionMethods/" target="_blank"><img src="https://zzzprojects.github.io/images/nuget/extension-methods-d.svg" alt="" /></a>
Z.ExtensionMethods.WithObjectNamespace | <a href="https://www.nuget.org/packages/Z.ExtensionMethods.WithObjectNamespace/" target="_blank"><img src="https://zzzprojects.github.io/images/nuget/extension-methods-with-object-namespace-v.svg" alt="download" /></a> <a href="https://www.nuget.org/packages/Z.ExtensionMethods.WithObjectNamespace/" target="_blank"><img src="https://zzzprojects.github.io/images/nuget/extension-methods-with-object-namespace-d.svg" alt="" /></a>
Z.ExtensionMethods.WithOneNamespace    | <a href="https://www.nuget.org/packages/Z.ExtensionMethods.WithOneNamespace/" target="_blank"><img src="https://zzzprojects.github.io/images/nuget/extension-methods-with-one-namespace-v.svg" alt="download" /></a> <a href="https://www.nuget.org/packages/Z.ExtensionMethods.WithOneNamespace/" target="_blank"><img src="https://zzzprojects.github.io/images/nuget/extension-methods-with-one-namespace-d.svg" alt="" /></a>
Z.ExtensionMethods.WithTwoNamespace    | <a href="https://www.nuget.org/packages/Z.ExtensionMethods.WithTwoNamespace/" target="_blank"><img src="https://zzzprojects.github.io/images/nuget/extension-methods-with-two-namespace-v.svg" alt="download" /></a> <a href="https://www.nuget.org/packages/Z.ExtensionMethods.WithTwoNamespace/" target="_blank"><img src="https://zzzprojects.github.io/images/nuget/extension-methods-with-two-namespace-d.svg" alt="" /></a>
Z.ExtensionMethods.WithNamespace       | <a href="https://www.nuget.org/packages/Z.ExtensionMethods.WithNamespace/" target="_blank"><img src="https://zzzprojects.github.io/images/nuget/extension-methods-with-namespace-v.svg" alt="download" /></a> <a href="https://www.nuget.org/packages/Z.ExtensionMethods.WithNamespace/" target="_blank"><img src="https://zzzprojects.github.io/images/nuget/extension-methods-with-namespace-d.svg" alt="" /></a>

So I believe there is a version for everyone. In your case, you could try the `Z.ExtensionMethods.WithNamespace`. All extensions methods are under the same namespaces.

Best Regards,

Jonathan

**Comment by jonleigh** [comment]
Ah, thanks Jonathan
