### ISSUE TITLE
Add SkipLines() method for StreamReader

### ISSUE THREAD

**Issue by adamfisher** [zzzprojects/Z.ExtensionMethods#20]
Sometimes you may want to skip the lines in a file when reading from it with a `StreamReader` so having a `SkipLines()` method would be super helpful.

```
public static class StreamReaderExtensions
{
	/// <summary>
	/// Skips the specified number of lines in a stream reader based on its current position.
	/// </summary>
	/// <param name="streamReader">The stream reader.</param>
	/// <param name="skipCount">The number of lines to skip.</param>
	private static void SkipLines(this StreamReader streamReader, int skipCount)
	{
		for (var i = 0; i < skipCount && !streamReader.EndOfStream; i++)
		{
			streamReader.ReadLine();
		}
	}
}
```

**Comment by adamfisher** [comment]
Created PR https://github.com/zzzprojects/Z.ExtensionMethods/pull/21 for the C# version of this.

**Comment by JonathanMagnan** [comment]
Hello @adamfisher ,

The v2.1.1 has been released with this extension methods.

Let me know if everything works as expected.

Thank a lot for your Pull ;)

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @adamfisher ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
