### ISSUE TITLE
Please add WhereIf for IQueryable

### ISSUE THREAD

**Issue by yunfandev** [zzzprojects/Z.ExtensionMethods#26]
### Description

```cs
    /// <summary>
    /// Filters a sequence of values based on a predicate if the judgement is matched.
    /// </summary>
    /// <typeparam name="TSource">The type of the elements of source.</typeparam>
    /// <param name="source">An <see cref="IQueryable{T}"/> to filter.</param>
    /// <param name="judgement">The judgement to decide whether the filter should take affect.</param>
    /// <param name="predicate">A function to test each element for a condition.</param>
    /// <returns>
    /// An <see cref="IQueryable{T}"/> that contains elements from the input sequence that satisfy the condition
    /// specified by predicate.
    /// </returns>
    public static IQueryable<TSource> WhereIf<TSource>(this IQueryable<TSource> source, bool judgement, Expression<Func<TSource, bool>> predicate)
    {
        if (!judgement)
        {
            return source;
        }

        return source.Where(predicate);
    }
```

**Comment by JonathanMagnan** [comment]
Hello @yunfandev ,

Thank you for reporting, we will look at it the next time we release this project (we are currently overloaded at this moment)

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by yunfandev** [comment]
Thanks!

**Comment by drpeck** [comment]
This would meet the same goal, but the code may be preferable.

https://khalidabuhakmeh.com/conditionally-apply-linq-clauses
