### ISSUE TITLE
String - NotIn documentation showing wrong method

### ISSUE THREAD

**Issue by ryanmunson8** [zzzprojects/Z.ExtensionMethods#35]
The `String - NotIn` documentation (https://csharp-extension.com/en/method/1002063/string-notin) is showing the implementation for the `String - In` method and the **View Source** link is pointing to the same incorrect source @ [String.In](https://github.com/zzzprojects/Z.ExtensionMethods/blob/master/src/Z.Core/System.String/_CoreObject/String.In.cs), but should point to [String.NotIn](https://github.com/zzzprojects/Z.ExtensionMethods/blob/master/src/Z.Core/System.String/_CoreObject/String.NotIn.cs)

**Comment by JonathanMagnan** [comment]
Hello @ryanmunson8 ,

Thank you for reporting.

The page has been updated.

Best Regards,

Jon
