### ISSUE TITLE
String.Copy() source is incorrect

### ISSUE THREAD

**Issue by NetMage** [zzzprojects/Z.ExtensionMethods#37]
## 1. Description
The page for [`String.Copy()`](https://csharp-extension.com/en/method/1002160/string-copy) shows the wrong source.

## 4. Any further technical details
The source shown is for `String.Concat()`

**Comment by JonathanMagnan** [comment]
Hello @NetMage ,

Thank you for reporting.

The source link has been updated, and the wrong text has been removed from the page.

We will surely look soon at what we can do with this website to improve it. I believe with Chat GPT, there is something more useful that we can really do on this website to make page be better indexed and be helpful to people looking for extension methods.

Best Regards,

Jon

**Comment by NetMage** [comment]
It looks like the page for `String.Copy` no longer includes the source on the page, just a link to the source. Other documentation pages embed the source after the link?

**Comment by JonathanMagnan** [comment]
Hello @NetMage ,

Yes, that's normal. This website is old, and we, unfortunately, lost the code source of it. So it was easier to simply remove this part and change the link directly in the database.

So, for now, only the link is included for this one.

Best Regards,

Jon
