### ISSUE TITLE
The comments in the String.Concat source are broken

### ISSUE THREAD

**Issue by NetMage** [zzzprojects/Z.ExtensionMethods#38]
## 1. Description
The comments in the source on the page for [`String.Concat`](https://csharp-extension.com/en/method/1002159/string-concat) are broken. They are missing references to the parameter names (e.g. "<returns>The concatenation of  and .").

**Comment by JonathanMagnan** [comment]
Hello @NetMage ,

Thank you for reporting.

The source has been fixed
