### ISSUE TITLE
Comments not compiled/distributed with nuget packages?

### ISSUE THREAD

**Issue by nicholashead** [zzzprojects/Z.ExtensionMethods#6]
I see the source code has comments on most methods/params, however the packaged/built version doesn't appear to? At least in my Visual Studio, they don't appear in the autocomplete list.

**Comment by JonathanMagnan** [comment]
Hello @nicholashead ,

Thank you for pointing me this,

I'm not sure to understand why it doesn't appear (tried on VS2013 and VS1017), but I will try to find the cause this weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @nicholashead ,

The v2.0.13 has been released,

The documentation now appears as expected.

Best Regards,

Jonathan

**Comment by nicholashead** [comment]
Thanks! I’ll check it out. Appreciate the help.
